spring:
  application:
    name: complaint-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/complaint?useUnicode=true&useSSL=false&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    hikari:
      connection-timeout: 60000
      minimum-idle: 5
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
  resources:
    # 添加资源映射
    static-locations: file:${complaint.picture.path}
  mvc:
    # 映射路径
    static-path-pattern: /picture/**
security:
  oauth2:
    resource:
#     从认证服务器获取用户信息，验证token权限，实现了单点登录，在认证服务器中拿到token后，带上该token访问其他服务器即可，非认证服务器都这样配置
      user-info-uri: http://localhost:9098/user-me
      prefer-token-info: false
server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
#   图片保存的根路径
complaint:
  picture:
    path: /Users/krystal/Pictures/complaint
